# Generated by Django 6.0.7 on 2026-07-14 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_plan_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Owner, Lawyer, Assistant, Expert', max_length=50)),
                ('permissions', models.JSONField(default=dict, help_text='Lista de permissões específicas')),
            ],
            options={
                'verbose_name': 'Papel (Role)',
                'verbose_name_plural': 'Papéis (Roles)',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.role')),
            ],
            options={
                'verbose_name': 'Vínculo (Membership)',
                'verbose_name_plural': 'Vínculos (Memberships)',
                'unique_together': {('user', 'office')},
            },
        ),
    ]
