# Generated by Django 6.0.7 on 2026-07-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ do Escritório', max_length=20, null=True, unique=True),
        ),
    ]
