# Generated by Django 6.0.7 on 2026-07-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domínio do cálculo (civil, trabalhista, etc)', max_length=50)),
                ('version_number', models.IntegerField(default=1)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versão de Cálculo',
                'verbose_name_plural': 'Versões de Cálculo',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('calculation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.calculationversion')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
        migrations.CreateModel(
            name='EconomicIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: IPCA, INPC, SELIC', max_length=50)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=8, help_text='Valor do índice no mês', max_digits=15)),
            ],
            options={
                'verbose_name': 'Índice Econômico',
                'verbose_name_plural': 'Índices Econômicos',
                'unique_together': {('name', 'date')},
            },
        ),
    ]
