# Generated by Django 6.0.7 on 2026-07-15 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('lawsuits', '0001_initial'),
        ('users', '0003_role_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculationversion',
            name='input_data',
            field=models.JSONField(help_text='Parâmetros exatos que geraram este resultado'),
        ),
        migrations.AlterField(
            model_name='calculationversion',
            name='output_data',
            field=models.JSONField(help_text='Resultado financeiro exato na época'),
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(help_text="Motor utilizado (ex: 'labor', 'civil')", max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculations', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calculations', to=settings.AUTH_USER_MODEL)),
                ('lawsuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculations', to='lawsuits.lawsuit')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='users.office')),
            ],
            options={
                'verbose_name': 'Cálculo',
                'verbose_name_plural': 'Cálculos',
            },
        ),
        migrations.AddField(
            model_name='calculationversion',
            name='calculation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.calculation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='calculationversion',
            unique_together={('calculation', 'version_number')},
        ),
        migrations.RemoveField(
            model_name='calculationversion',
            name='domain',
        ),
    ]
