# Generated by Django 6.0.7 on 2026-07-14 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0003_role_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnj_number', models.CharField(db_index=True, help_text='Número unificado do CNJ', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('ARCHIVED', 'Arquivado'), ('SUSPENDED', 'Suspenso')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informações adicionais do processo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuits', to='clients.client')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuits', to='users.office')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'unique_together': {('office', 'cnj_number')},
            },
        ),
    ]
